# -*- coding: utf-8 -*-
"""
demo_mock_interview.py — "Try a Mock Interview" demo (pick a track, get questions)
=================================================================================
A lightweight, login-free demo: pick a track (or tap a popular one), choose a
difficulty, and get 5 real interview questions instantly. The full experience
(AI scoring, feedback, voice answers, report card) is gated behind a
"Start Practicing Now" CTA that opens the live app.

Works with OR without a key:
    • If GROQ_API_KEY is set, fresh questions are generated by AI.
    • Otherwise it falls back to a built-in question bank so the demo always works.

Config (Streamlit secrets or env):
    GROQ_API_KEY   (optional — free key: https://console.groq.com/)

Embed:  import demo_mock_interview; demo_mock_interview.render_demo_mock_interview()
"""

import os
import random
import streamlit as st

# Where the "Start Practicing Now" button sends users (the live full app).
FULL_APP_URL = "https://aijavamockinterview-110.streamlit.app/~/+/#ml-login"


def _cfg(key, default=""):
    v = os.environ.get(key)
    if v:
        return v
    try:
        if key in st.secrets:
            return st.secrets[key]
    except Exception:
        pass
    return default


# Tracks shown in the dropdown (mirrors the mock-interview modes in the main app).
TRACKS = [
    "Core Java", "Python", "DevOps", "AWS", "SQL",
    "Spring Boot", "Microservices", "System Design", "AI Agents", "DSA",
]

POPULAR_TRACKS = ["Core Java", "Python", "SQL", "AWS", "System Design", "AI Agents"]

DIFFICULTIES = ["Junior (0-2 yrs)", "Mid (2-5 yrs)", "Senior (5+ yrs)"]


# ── Built-in fallback bank (used when no GROQ_API_KEY is set) ──
# Keyed by track → difficulty-tier ("junior" / "mid" / "senior").
_BANK = {
    "Core Java": {
        "junior": [
            "What is the difference between `==` and `.equals()` in Java?",
            "Explain the four pillars of OOP with a quick example of each.",
            "What is the difference between an interface and an abstract class?",
            "How does the `String` pool work, and why are Strings immutable?",
            "What happens during autoboxing, and what pitfall can it cause in loops?",
        ],
        "mid": [
            "How does the JVM handle garbage collection, and what are the generations?",
            "Explain the difference between `HashMap`, `LinkedHashMap`, and `TreeMap`.",
            "What is the difference between `synchronized` and a `ReentrantLock`?",
            "How do `Stream`s differ from collections, and when would lazy evaluation matter?",
            "What is the difference between `Comparable` and `Comparator`?",
        ],
        "senior": [
            "Design a thread-safe in-memory cache with TTL eviction. Walk through the tradeoffs.",
            "How would you diagnose and fix a memory leak in a long-running JVM service?",
            "Explain the Java Memory Model and how `volatile` and `happens-before` relate.",
            "When would you choose virtual threads (Project Loom) over a thread pool?",
            "Explain how you would design a plugin architecture using the service-loader pattern.",
        ],
    },
    "Python": {
        "junior": [
            "What is the difference between a list, a tuple, and a set?",
            "Explain how Python's `for` loop uses iterators under the hood.",
            "What are `*args` and `**kwargs`, and when do you use them?",
            "What is a list comprehension, and rewrite a simple loop as one.",
            "What is the difference between `is` and `==`?",
        ],
        "mid": [
            "Explain the GIL and how it affects CPU-bound vs I/O-bound work.",
            "What is a decorator? Write one that times a function's execution.",
            "Explain generators and how `yield` differs from `return`.",
            "How does `asyncio` achieve concurrency without threads?",
            "What is the difference between a shallow copy and a deep copy?",
        ],
        "senior": [
            "Design a rate limiter in Python. Discuss token-bucket vs sliding-window.",
            "How would you profile and optimize a slow data-processing pipeline?",
            "Explain how Python's memory management and reference counting work.",
            "When would you reach for multiprocessing over asyncio, and why?",
            "How would you design a caching layer with an LRU eviction policy in Python?",
        ],
    },
    "DevOps": {
        "junior": [
            "What is the difference between a container and a virtual machine?",
            "Explain what a CI/CD pipeline does at a high level.",
            "What is the purpose of a Dockerfile, and name three common instructions.",
            "What is the difference between `git merge` and `git rebase`?",
            "What is the difference between an image and a running container?",
        ],
        "mid": [
            "Explain the components of a Kubernetes cluster (pods, nodes, services).",
            "How would you design a zero-downtime deployment (blue-green vs canary)?",
            "What is Infrastructure as Code, and why is Terraform state important?",
            "How do you handle secrets in a CI/CD pipeline securely?",
            "How would you roll back a bad Kubernetes deployment quickly?",
        ],
        "senior": [
            "Design an observability stack for a microservices platform (logs, metrics, traces).",
            "How would you architect multi-region failover for a critical service?",
            "Walk through debugging a production outage caused by a bad rollout.",
            "How do you keep a Kubernetes cluster secure and cost-efficient at scale?",
            "Design a CI/CD pipeline for a fleet of microservices with independent releases.",
        ],
    },
    "AWS": {
        "junior": [
            "What is the difference between EC2, Lambda, and Fargate?",
            "Explain what an S3 bucket is and a few common storage classes.",
            "What is an IAM role, and how does it differ from an IAM user?",
            "What is a VPC, and why would you use a private subnet?",
            "What is the difference between a security group and a network ACL?",
        ],
        "mid": [
            "How would you design a serverless REST API on AWS?",
            "Explain the difference between RDS and DynamoDB and when to use each.",
            "How do you secure traffic between services inside a VPC?",
            "What are the tradeoffs of SQS vs SNS vs EventBridge?",
            "How would you design least-privilege IAM for a team of developers?",
        ],
        "senior": [
            "Design a highly available, auto-scaling web platform on AWS. Justify each choice.",
            "How would you reduce a large monthly AWS bill without hurting reliability?",
            "Explain a disaster-recovery strategy and the RTO/RPO tradeoffs involved.",
            "How would you architect a multi-account AWS organization for a large company?",
            "Design a globally low-latency read path using CloudFront and edge caching.",
        ],
    },
    "SQL": {
        "junior": [
            "What is the difference between `INNER JOIN` and `LEFT JOIN`?",
            "Explain the difference between `WHERE` and `HAVING`.",
            "What is a primary key vs a foreign key?",
            "Write a query to find the second-highest salary from an `employees` table.",
            "What is the difference between `DELETE`, `TRUNCATE`, and `DROP`?",
        ],
        "mid": [
            "What is an index, and how does it speed up (or slow down) queries?",
            "Explain database normalization up to 3NF with an example.",
            "What is the difference between a transaction's isolation levels?",
            "How would you find and fix a slow query?",
            "What is the difference between a clustered and a non-clustered index?",
        ],
        "senior": [
            "Design the schema for a multi-tenant SaaS app and discuss the tradeoffs.",
            "How do you scale a relational database (replication, sharding, partitioning)?",
            "Explain how a window function works and give a real use case.",
            "Walk through diagnosing a deadlock in a high-traffic database.",
            "How would you design an audit-log table that stays fast as it grows to billions of rows?",
        ],
    },
    "Spring Boot": {
        "junior": [
            "What is dependency injection, and how does Spring provide it?",
            "What is the difference between `@Component`, `@Service`, and `@Repository`?",
            "How does Spring Boot auto-configuration work at a high level?",
            "What is the purpose of `application.properties` / `application.yml`?",
            "What is a Spring bean's scope, and name the common scopes.",
        ],
        "mid": [
            "How do you handle exceptions globally in a Spring Boot REST API?",
            "Explain the request lifecycle of a Spring MVC controller.",
            "How would you secure a REST API with Spring Security and JWT?",
            "What is the difference between `@Transactional` propagation levels?",
            "How would you add caching to a hot endpoint with Spring Cache?",
        ],
        "senior": [
            "Design a resilient microservice with retries, timeouts, and circuit breakers.",
            "How would you profile and reduce startup time of a large Spring Boot app?",
            "Explain how you'd implement distributed tracing across services.",
            "How do you manage configuration and secrets across many environments?",
            "Design health checks and graceful shutdown for a service behind a load balancer.",
        ],
    },
    "Microservices": {
        "junior": [
            "What is a microservice, and how does it differ from a monolith?",
            "What is an API gateway, and why is it useful?",
            "How do services typically communicate (sync vs async)?",
            "What is service discovery?",
            "What is the difference between orchestration and choreography?",
        ],
        "mid": [
            "How do you handle a distributed transaction across services (saga pattern)?",
            "Explain eventual consistency and where it's acceptable.",
            "How would you design idempotent APIs, and why does it matter?",
            "What strategies help prevent cascading failures?",
            "How would you implement distributed tracing across service boundaries?",
        ],
        "senior": [
            "Design an event-driven order-processing system end to end.",
            "How do you version and evolve APIs without breaking consumers?",
            "Explain how you'd roll out a schema change across many services safely.",
            "How would you decompose a large monolith into microservices incrementally?",
            "Design a reliable outbox pattern to publish events without dual-write bugs.",
        ],
    },
    "System Design": {
        "junior": [
            "What is the difference between horizontal and vertical scaling?",
            "What is a load balancer, and where does it sit in an architecture?",
            "What is caching, and name two places you might add a cache.",
            "What is the difference between SQL and NoSQL databases?",
            "What is a CDN, and what problem does it solve?",
        ],
        "mid": [
            "Design a URL shortener like bit.ly. Walk through the data model.",
            "How would you design a rate limiter for a public API?",
            "Explain the CAP theorem with a concrete tradeoff example.",
            "How would you design a news feed for a social app?",
            "How would you design a distributed rate limiter that works across many servers?",
        ],
        "senior": [
            "Design a globally distributed chat system like WhatsApp.",
            "Design the backend for a video-streaming service at scale.",
            "How would you design a system to handle 1M writes per second?",
            "Design a distributed job scheduler with exactly-once guarantees.",
            "Design a globally distributed key-value store and discuss consistency tradeoffs.",
        ],
    },
    "AI Agents": {
        "junior": [
            "What is an LLM agent, and how does it differ from a plain chatbot?",
            "What is a 'tool' in an agent, and why do agents call tools?",
            "Explain what a system prompt does in an agent.",
            "What is RAG (retrieval-augmented generation) at a high level?",
            "What is the difference between an agent's short-term and long-term memory?",
        ],
        "mid": [
            "How does a ReAct-style agent loop (reason → act → observe) work?",
            "How would you stop an agent from getting stuck in an infinite loop?",
            "Explain how a vector database supports semantic search in RAG.",
            "How do you evaluate whether an agent is actually reliable?",
            "How would you design retries and fallbacks when a tool call fails?",
        ],
        "senior": [
            "Design a multi-agent system where agents hand off tasks. Discuss coordination.",
            "How would you control cost and latency in a production agent pipeline?",
            "How do you make tool-calling robust to malformed or hostile inputs?",
            "Design guardrails and evals for an agent that takes real-world actions.",
            "How would you design a caching + batching layer to cut LLM cost by 10x?",
        ],
    },
    "DSA": {
        "junior": [
            "What is the time complexity of searching in a sorted array with binary search?",
            "Explain the difference between an array and a linked list.",
            "What is a stack, and give one real-world use case.",
            "Reverse a string in place — describe your approach.",
            "What is the time and space complexity of merge sort?",
        ],
        "mid": [
            "Find whether a linked list has a cycle. What's the optimal approach?",
            "Explain how a hash map achieves average O(1) lookups.",
            "Given an array, find two numbers that sum to a target. Optimize it.",
            "What is the difference between BFS and DFS, and when to use each?",
            "Detect if a string has all unique characters without extra data structures.",
        ],
        "senior": [
            "Design an LRU cache with O(1) get and put. Which data structures?",
            "Find the median of two sorted arrays in logarithmic time.",
            "Explain dynamic programming using the edit-distance problem.",
            "Serialize and deserialize a binary tree — walk through your design.",
            "Given a stream of numbers, return the running median efficiently.",
        ],
    },
}

# A short "what a strong answer covers" hint for the first sample question, per track.
_ANSWER_HINTS = {
    "Core Java": "A strong answer notes `==` compares references while `.equals()` compares "
                 "logical value, and that `.equals()`/`hashCode()` should be overridden together.",
    "Python": "A strong answer covers mutability (list mutable, tuple immutable), that sets are "
              "unordered and unique, and the performance/use-case tradeoffs of each.",
    "DevOps": "A strong answer explains that containers share the host kernel (lightweight, fast) "
              "while VMs virtualize hardware with a full guest OS (heavier, stronger isolation).",
    "AWS": "A strong answer contrasts EC2 (you manage the server), Lambda (event-driven, "
           "no server management), and Fargate (serverless containers), with cost/latency tradeoffs.",
    "SQL": "A strong answer explains `INNER JOIN` returns only matching rows while `LEFT JOIN` keeps "
           "all left-table rows with NULLs where there's no match.",
    "Spring Boot": "A strong answer defines DI as inversion of control, and shows how Spring's "
                   "container wires beans so classes don't construct their own dependencies.",
    "Microservices": "A strong answer covers independent deployability, bounded contexts, and the "
                     "operational tradeoffs (network calls, data consistency) vs a monolith.",
    "System Design": "A strong answer explains horizontal scaling adds more machines (better for "
                     "availability) while vertical scaling grows one machine (simpler, but a ceiling).",
    "AI Agents": "A strong answer describes an agent as an LLM that plans and calls tools in a loop "
                 "toward a goal, versus a chatbot that just responds turn-by-turn.",
    "DSA": "A strong answer states binary search is O(log n) because it halves the search space each "
           "step, and notes it requires the array to be sorted.",
}


def _tier(difficulty):
    d = difficulty.lower()
    if d.startswith("senior"):
        return "senior"
    if d.startswith("mid"):
        return "mid"
    return "junior"


def _bank_questions(track, difficulty, n):
    tier = _tier(difficulty)
    track_bank = _BANK.get(track) or _BANK["Core Java"]
    pool = list(track_bank.get(tier, [])) or list(track_bank.get("junior", []))
    random.shuffle(pool)
    return pool[:n]


def generate_questions(track, difficulty, n=5):  # noqa: demo shows all 5
    """Return (questions, source_label). Uses Groq if a key is set, else the bank."""
    api_key = _cfg("GROQ_API_KEY")
    if api_key:
        try:
            from groq import Groq
            client = Groq(api_key=api_key)
            prompt = (
                f"You are an expert {track} interviewer. Generate exactly {n} unique "
                f"interview questions for topic '{track}' at difficulty '{difficulty}'.\n"
                f"Rules:\n"
                f"- Return ONLY the questions, one per line, numbered 1. 2. 3.\n"
                f"- No answers, no explanations, no extra text.\n"
                f"- Vary format: conceptual, coding, scenario, debug, design."
            )
            res = client.chat.completions.create(
                model="llama-3.1-8b-instant",
                messages=[
                    {"role": "system", "content": f"You are a senior {track} technical interviewer."},
                    {"role": "user", "content": prompt},
                ],
                stream=False,
                temperature=1.0,
                top_p=0.95,
            )
            raw = res.choices[0].message.content.strip()
            qs = []
            for line in raw.split("\n"):
                line = line.strip()
                if line and line[0].isdigit():
                    if "." in line[:3]:
                        line = line.split(".", 1)[1].strip()
                    qs.append(line)
            if qs:
                return qs[:n], "🤖 AI generated"
        except Exception:
            pass  # fall back to bank silently — keeps the demo alive
    return _bank_questions(track, difficulty, n), "📖 Sample bank"


def render_demo_mock_interview():
    st.title("🎤 Try a Mock Interview")
    st.caption("Pick a track, choose your level, and get real interview questions — instant, no login.")

    c1, c2 = st.columns([2, 1])
    track = c1.selectbox("Track / role", TRACKS, index=0)
    difficulty = c2.selectbox("Difficulty", DIFFICULTIES, index=0)

    st.caption("Popular tracks — tap to try:")
    chip_cols = st.columns(len(POPULAR_TRACKS))
    picked = None
    for i, ch in enumerate(POPULAR_TRACKS):
        if chip_cols[i].button(ch, key=f"track_chip_{ch}"):
            picked = ch

    do_start = st.button("🎯 Start Demo Interview", type="primary")

    chosen = picked or (track if do_start else "")
    if not chosen:
        return

    with st.spinner(f"Preparing '{chosen}' questions…"):
        questions, source_label = generate_questions(chosen, difficulty, n=5)

    if not questions:
        st.info(f"No questions available for '{chosen}'. Try another track.")
        return

    demo_limit = 5  # show a full set of 5 sample questions
    shown = questions[:demo_limit]

    st.markdown(
        f"### {chosen} — {difficulty}  "
        f"<span style='font-size:13px;opacity:.7'>({source_label})</span>",
        unsafe_allow_html=True,
    )
    st.caption(f"Here are {len(shown)} sample questions to warm up 👇")

    for i, q in enumerate(shown, start=1):
        with st.container(border=True):
            st.markdown(f"#### Question {i}")
            st.write(q)
            if i == 1:
                hint = _ANSWER_HINTS.get(chosen)
                if hint:
                    with st.expander("💡 What a strong answer covers"):
                        st.write(hint)

    # Teaser: the demo just lists questions — the real value (answering + being
    # scored) is gated behind the CTA.
    st.markdown(
        f"""<div style="margin-top:18px;padding:22px 26px;border-radius:16px;text-align:center;
        background:linear-gradient(135deg,#7c3aed,#0ea5e9);color:#fff;">
        <div style="font-size:20px;font-weight:800;margin-bottom:6px;">
        🔒 Ready to actually answer these?</div>
        <div style="opacity:.95;font-size:15px;">This free demo just shows the questions.
        Practice a full mock interview to answer by <b>voice or text</b>, get
        <b>instant AI feedback &amp; a 0–10 score</b> per answer, unlimited fresh
        questions, and a <b>report card</b> at the end.</div></div>""",
        unsafe_allow_html=True,
    )

    cta = st.columns([1, 2, 1])
    with cta[1]:
        st.link_button(
            "🚀 Start Practicing Now →",
            FULL_APP_URL,
            type="primary",
            use_container_width=True,
        )
    st.caption("Free demo. Full scoring, voice answers, and report cards unlock in the live app.")


if __name__ == "__main__":
    st.set_page_config(page_title="Try a Mock Interview", page_icon="🎤", layout="centered")
    render_demo_mock_interview()
