# -*- coding: utf-8 -*-
"""
demo_class10_odia.py — Class 10 (Odia medium) MCQ practice test
===============================================================
A login-free practice test for BSE Odisha Class 10 students. Pick a subject
(Math / Science / English / Social Science), answer bilingual (Odia + English)
multiple-choice questions, then get a score with an explanation for every
question.

Works with OR without a key:
    • If GROQ_API_KEY is set, fresh MCQs are generated by AI (bilingual).
    • Otherwise it uses the built-in question bank, so it always works.

Embed:  import demo_class10_odia; demo_class10_odia.render_demo_class10_mcq()
"""

import json
import os
import random

import streamlit as st


def _cfg(key, default=""):
    v = os.environ.get(key)
    if v:
        return v
    try:
        if key in st.secrets:
            return st.secrets[key]
    except Exception:
        pass
    return default


# Subject label (bilingual) -> emoji
SUBJECTS = {
    "ଗଣିତ (Math)": "🧮",
    "ବିଜ୍ଞାନ (Science)": "🔬",
    "ଇଂରାଜୀ (English)": "🔤",
    "ସାମାଜିକ ବିଜ୍ଞାନ (Social Science)": "🌍",
}

# Each item: {"q", "options" (4), "answer" (0-based index), "explain"}
MCQ_BANK = {
    "ଗଣିତ (Math)": [
        {"q": "ଦ୍ୱିଘାତ ସମୀକରଣର ସର୍ବାଧିକ କେତୋଟି ମୂଳ ଥାଏ? (Max number of roots of a quadratic equation?)",
         "options": ["1", "2", "3", "4"], "answer": 1,
         "explain": "ଦ୍ୱିଘାତ ସମୀକରଣର ଘାତ (degree) 2, ତେଣୁ ସର୍ବାଧିକ 2ଟି ମୂଳ ଥାଏ। / Degree 2 ⇒ at most 2 roots."},
        {"q": "sin 30° ର ମାନ କେତେ? (Value of sin 30°?)",
         "options": ["1", "1/2", "√3/2", "0"], "answer": 1,
         "explain": "sin 30° = 1/2।"},
        {"q": "cos 0° ର ମାନ କେତେ? (Value of cos 0°?)",
         "options": ["0", "1/2", "1", "√3/2"], "answer": 2,
         "explain": "cos 0° = 1।"},
        {"q": "tan 45° ର ମାନ କେତେ? (Value of tan 45°?)",
         "options": ["0", "1", "√3", "1/√3"], "answer": 1,
         "explain": "tan 45° = 1।"},
        {"q": "ବୃତ୍ତର କ୍ଷେତ୍ରଫଳ କେତେ? (r = ବ୍ୟାସାର୍ଦ୍ଧ) / Area of a circle (r = radius)?",
         "options": ["2πr", "πr²", "πd", "2πr²"], "answer": 1,
         "explain": "ବୃତ୍ତର କ୍ଷେତ୍ରଫଳ = πr²। / Area of a circle = πr²."},
        {"q": "ଦୁଇ ସଂଖ୍ୟାର HCF × LCM କାହା ସହ ସମାନ? (For two numbers, HCF × LCM equals?)",
         "options": ["ସେମାନଙ୍କ ଯୋଗଫଳ (their sum)", "ସେମାନଙ୍କ ଗୁଣନଫଳ (their product)",
                     "ସେମାନଙ୍କ ଅନ୍ତର (their difference)", "1"], "answer": 1,
         "explain": "HCF × LCM = ଦୁଇ ସଂଖ୍ୟାର ଗୁଣନଫଳ। / HCF × LCM = product of the two numbers."},
        {"q": "π (pi)ର ଆନୁମାନିକ ମାନ କେତେ? (Approximate value of π?)",
         "options": ["2.14", "3.14", "1.41", "1.73"], "answer": 1,
         "explain": "π ≈ 3.14 (ବା 22/7)।"},
        {"q": "ଏକ ବର୍ଗର କ୍ଷେତ୍ରଫଳ 64 ବର୍ଗ ମିଟର ହେଲେ ବାହୁ କେତେ? (Side of a square with area 64 m²?)",
         "options": ["6 m", "7 m", "8 m", "16 m"], "answer": 2,
         "explain": "ବାହୁ = √64 = 8 ମିଟର। / Side = √64 = 8 m."},
        {"q": "5, 10, 15, 20 ... ଏହା କେଉଁ ପ୍ରକାର ଶ୍ରେଣୀ? (What kind of sequence is 5,10,15,20…?)",
         "options": ["ଗୁଣୋତ୍ତର (GP)", "ସମାନ୍ତର (AP)", "ଫିବୋନାକ୍କି", "କୌଣସିଟି ନୁହେଁ"], "answer": 1,
         "explain": "ପ୍ରତ୍ୟେକ ପଦ ମଧ୍ୟରେ ସମାନ ଅନ୍ତର (5) ଅଛି ⇒ ସମାନ୍ତର ଶ୍ରେଣୀ (Arithmetic Progression)।"},
        {"q": "ପାଇଥାଗୋରସ୍ ଉପପାଦ୍ୟ କେଉଁ ତ୍ରିଭୁଜରେ ଲାଗୁ ହୁଏ? (Pythagoras theorem applies to which triangle?)",
         "options": ["ସମବାହୁ (equilateral)", "ସମକୋଣୀ (right-angled)", "ସ୍ଥୂଳକୋଣୀ (obtuse)", "ସବୁ ତ୍ରିଭୁଜ"],
         "answer": 1, "explain": "କେବଳ ସମକୋଣୀ ତ୍ରିଭୁଜରେ: କର୍ଣ୍ଣ² = ଭୂମି² + ଲମ୍ବ²।"},
    ],
    "ବିଜ୍ଞାନ (Science)": [
        {"q": "ଜଳର ରାସାୟନିକ ସୂତ୍ର କ'ଣ? (Chemical formula of water?)",
         "options": ["CO₂", "H₂O", "O₂", "NaCl"], "answer": 1,
         "explain": "ଜଳ = H₂O (2ଟି ହାଇଡ୍ରୋଜେନ୍ + 1ଟି ଅମ୍ଳଜାନ)।"},
        {"q": "ଆଲୋକ ସଂଶ୍ଳେଷଣ କୋଷର କେଉଁ ଅଙ୍ଗାଣୁରେ ଘଟେ? (Where does photosynthesis occur?)",
         "options": ["ମାଇଟୋକଣ୍ଡ୍ରିଆ", "ନ୍ୟୁକ୍ଲିୟସ୍", "କ୍ଲୋରୋପ୍ଲାଷ୍ଟ (chloroplast)", "ରାଇବୋଜୋମ୍"], "answer": 2,
         "explain": "କ୍ଲୋରୋପ୍ଲାଷ୍ଟରେ ଥିବା କ୍ଲୋରୋଫିଲ୍ ଆଲୋକ ଶୋଷଣ କରି ଆଲୋକ ସଂଶ୍ଳେଷଣ କରାଏ।"},
        {"q": "ବିଦ୍ୟୁତ୍ ଧାରାର SI ଏକକ କ'ଣ? (SI unit of electric current?)",
         "options": ["ଭୋଲ୍ଟ (Volt)", "ଆମ୍ପିୟର (Ampere)", "ୱାଟ୍ (Watt)", "ଓହମ୍ (Ohm)"], "answer": 1,
         "explain": "ବିଦ୍ୟୁତ୍ ଧାରାର ଏକକ ଆମ୍ପିୟର (A)।"},
        {"q": "ଅମ୍ଳର pH ମାନ ସାଧାରଣତଃ କେତେ? (pH value of an acid is usually?)",
         "options": ["7 ରୁ କମ୍ (<7)", "ଠିକ୍ 7", "7 ରୁ ଅଧିକ (>7)", "14"], "answer": 0,
         "explain": "ଅମ୍ଳ pH < 7; ନିରପେକ୍ଷ (neutral) = 7; କ୍ଷାର (base) > 7।"},
        {"q": "ସୂର୍ଯ୍ୟଙ୍କ ନିକଟତମ ଗ୍ରହ କେଉଁଟି? (Nearest planet to the Sun?)",
         "options": ["ପୃଥିବୀ (Earth)", "ଶୁକ୍ର (Venus)", "ବୁଧ (Mercury)", "ମଙ୍ଗଳ (Mars)"], "answer": 2,
         "explain": "ବୁଧ (Mercury) ସୂର୍ଯ୍ୟଙ୍କ ନିକଟତମ ଗ୍ରହ।"},
        {"q": "ବଳର SI ଏକକ କ'ଣ? (SI unit of force?)",
         "options": ["ଜୁଲ୍ (Joule)", "ନ୍ୟୁଟନ୍ (Newton)", "ପାସ୍କାଲ୍ (Pascal)", "ୱାଟ୍ (Watt)"], "answer": 1,
         "explain": "ବଳର ଏକକ ନ୍ୟୁଟନ୍ (N)।"},
        {"q": "ଧ୍ୱନି ଶୂନ୍ୟସ୍ଥାନ (vacuum)ରେ ଗତି କରିପାରେ କି? (Can sound travel through vacuum?)",
         "options": ["ହଁ (Yes)", "ନା (No)", "କେବଳ ରାତିରେ", "କେବଳ ଜଳରେ"], "answer": 1,
         "explain": "ଧ୍ୱନିକୁ ମାଧ୍ୟମ (medium) ଆବଶ୍ୟକ; ଶୂନ୍ୟସ୍ଥାନରେ ଏହା ଗତି କରିପାରେ ନାହିଁ।"},
        {"q": "ରକ୍ତରେ ଅମ୍ଳଜାନ ବହନ କରୁଥିବା ଉପାଦାନ କ'ଣ? (What carries oxygen in blood?)",
         "options": ["ପ୍ଲାଜମା", "ହିମୋଗ୍ଲୋବିନ୍ (Haemoglobin)", "ପ୍ଲେଟଲେଟ୍", "ଶ୍ୱେତ ରକ୍ତକଣିକା"], "answer": 1,
         "explain": "ଲୋହିତ ରକ୍ତକଣିକାର ହିମୋଗ୍ଲୋବିନ୍ ଅମ୍ଳଜାନ ବହନ କରେ ଓ ରକ୍ତକୁ ଲାଲ୍ ରଙ୍ଗ ଦିଏ।"},
        {"q": "ମାନବ ଶରୀରରେ କେତୋଟି ହାଡ଼ ଥାଏ (ବୟସ୍କ)? (Number of bones in an adult human body?)",
         "options": ["206", "201", "212", "300"], "answer": 0,
         "explain": "ବୟସ୍କ ମାନବ ଶରୀରରେ 206ଟି ହାଡ଼ ଥାଏ।"},
        {"q": "LED ର ପୂର୍ଣ୍ଣ ରୂପ କ'ଣ? (Full form of LED?)",
         "options": ["Light Emitting Diode", "Low Energy Device", "Light Energy Detector",
                     "Linear Electric Diode"], "answer": 0,
         "explain": "LED = Light Emitting Diode (ଆଲୋକ ନିର୍ଗତ କରୁଥିବା ଡାଇଓଡ୍)।"},
    ],
    "ଇଂରାଜୀ (English)": [
        {"q": "Choose the correct plural of 'child'. (‘child’ ର ବହୁବଚନ)",
         "options": ["childs", "childes", "children", "child"], "answer": 2,
         "explain": "‘Child’ ର ବହୁବଚନ (plural) ‘children’।"},
        {"q": "Choose the past tense of 'go'. (‘go’ ର ଅତୀତ କାଳ)",
         "options": ["goed", "went", "gone", "going"], "answer": 1,
         "explain": "‘Go’ ର past tense ‘went’; past participle ‘gone’।"},
        {"q": "Antonym (ବିପରୀତ ଅର୍ଥ) of 'brave'?",
         "options": ["bold", "cowardly", "strong", "fearless"], "answer": 1,
         "explain": "‘Brave’ (ସାହସୀ) ର ବିପରୀତ ‘cowardly’ (ଭୀରୁ)।"},
        {"q": "Fill in the blank: She ___ to school every day.",
         "options": ["go", "goes", "gone", "going"], "answer": 1,
         "explain": "Singular subject ‘She’ ସହିତ ‘goes’ (present simple) ବ୍ୟବହୃତ ହୁଏ।"},
        {"q": "Identify the noun: 'The dog runs fast.' (ବିଶେଷ୍ୟ ବାଛନ୍ତୁ)",
         "options": ["runs", "fast", "dog", "the"], "answer": 2,
         "explain": "‘Dog’ ଏକ noun (ବିଶେଷ୍ୟ)।"},
        {"q": "Choose the correctly spelled word. (ସଠିକ୍ ବନାନ)",
         "options": ["recieve", "receive", "receeve", "resieve"], "answer": 1,
         "explain": "ସଠିକ୍ ବନାନ ‘receive’ (i before e, except after c)।"},
        {"q": "Synonym (ସମାନ ଅର୍ଥ) of 'happy'?",
         "options": ["sad", "angry", "glad", "tired"], "answer": 2,
         "explain": "‘Happy’ (ଖୁସି) ର ସମାନାର୍ଥକ ‘glad’।"},
        {"q": "Which is a pronoun? (ସର୍ବନାମ କେଉଁଟି?)",
         "options": ["run", "she", "blue", "quickly"], "answer": 1,
         "explain": "‘She’ ଏକ pronoun (ସର୍ବନାମ)।"},
    ],
    "ସାମାଜିକ ବିଜ୍ଞାନ (Social Science)": [
        {"q": "ଭାରତର ଜାତୀୟ ପଶୁ କେଉଁଟି? (National animal of India?)",
         "options": ["ସିଂହ (Lion)", "ବାଘ (Tiger)", "ହାତୀ (Elephant)", "ମୟୂର (Peacock)"], "answer": 1,
         "explain": "ଭାରତର ଜାତୀୟ ପଶୁ ବଙ୍ଗୀୟ ବାଘ (Royal Bengal Tiger)।"},
        {"q": "ଓଡ଼ିଶାର ରାଜଧାନୀ କେଉଁଠି? (Capital of Odisha?)",
         "options": ["କଟକ (Cuttack)", "ପୁରୀ (Puri)", "ଭୁବନେଶ୍ୱର (Bhubaneswar)", "ସମ୍ବଲପୁର"], "answer": 2,
         "explain": "ଓଡ଼ିଶାର ରାଜଧାନୀ ଭୁବନେଶ୍ୱର।"},
        {"q": "ଭାରତ କେଉଁ ବର୍ଷ ସ୍ୱାଧୀନତା ପାଇଲା? (Year of India's independence?)",
         "options": ["1942", "1945", "1947", "1950"], "answer": 2,
         "explain": "ଭାରତ 15 ଅଗଷ୍ଟ 1947ରେ ସ୍ୱାଧୀନ ହେଲା।"},
        {"q": "ଭାରତୀୟ ସମ୍ବିଧାନ କେବେ କାର୍ଯ୍ୟକାରୀ ହେଲା? (When did the Indian Constitution come into effect?)",
         "options": ["15 Aug 1947", "26 Jan 1950", "26 Nov 1949", "2 Oct 1950"], "answer": 1,
         "explain": "ଭାରତୀୟ ସମ୍ବିଧାନ 26 ଜାନୁଆରୀ 1950ରୁ କାର୍ଯ୍ୟକାରୀ ହେଲା (ଗଣତନ୍ତ୍ର ଦିବସ)।"},
        {"q": "ପୃଥିବୀର ସର୍ବୋଚ୍ଚ ପର୍ବତ ଶୃଙ୍ଗ କେଉଁଟି? (Highest mountain peak on Earth?)",
         "options": ["K2", "କାଞ୍ଚନଜଙ୍ଘା", "ମାଉଣ୍ଟ ଏଭରେଷ୍ଟ (Everest)", "ନନ୍ଦା ଦେବୀ"], "answer": 2,
         "explain": "ମାଉଣ୍ଟ ଏଭରେଷ୍ଟ (8,849 ମି) ପୃଥିବୀର ସର୍ବୋଚ୍ଚ ଶୃଙ୍ଗ।"},
        {"q": "ଭାରତର ଜାତୀୟ ନଦୀ କେଉଁଟି? (National river of India?)",
         "options": ["ମହାନଦୀ", "ଗଙ୍ଗା (Ganga)", "ଯମୁନା", "ଗୋଦାବରୀ"], "answer": 1,
         "explain": "ଗଙ୍ଗା ଭାରତର ଜାତୀୟ ନଦୀ।"},
        {"q": "ଓଡ଼ିଶାର ରଥଯାତ୍ରା କେଉଁ ସହରରେ ପ୍ରସିଦ୍ଧ? (Rath Yatra is famous in which city of Odisha?)",
         "options": ["କଟକ", "ପୁରୀ (Puri)", "କୋଣାର୍କ", "ବ୍ରହ୍ମପୁର"], "answer": 1,
         "explain": "ଜଗନ୍ନାଥ ରଥଯାତ୍ରା ପୁରୀରେ ବିଶ୍ୱପ୍ରସିଦ୍ଧ।"},
        {"q": "ଭାରତର ପ୍ରଥମ ପ୍ରଧାନମନ୍ତ୍ରୀ କିଏ ଥିଲେ? (First Prime Minister of India?)",
         "options": ["ମହାତ୍ମା ଗାନ୍ଧୀ", "ଜବାହରଲାଲ ନେହେରୁ (Nehru)", "ସର୍ଦ୍ଦାର ପଟେଲ", "ଡକ୍ଟର ରାଜେନ୍ଦ୍ର ପ୍ରସାଦ"],
         "answer": 1, "explain": "ପଣ୍ଡିତ ଜବାହରଲାଲ ନେହେରୁ ଭାରତର ପ୍ରଥମ ପ୍ରଧାନମନ୍ତ୍ରୀ।"},
    ],
}


def _ai_generate(subject, n):
    """Optional: generate bilingual MCQs via Groq. Returns list or [] on failure."""
    api_key = _cfg("GROQ_API_KEY")
    if not api_key:
        return []
    try:
        from groq import Groq
        client = Groq(api_key=api_key)
        prompt = (
            f"Generate {n} multiple-choice questions for BSE Odisha Class 10, subject "
            f"'{subject}'. Each question and its options must be BILINGUAL (Odia first, "
            f"then English in brackets). Return ONLY valid JSON: a list of objects with keys "
            f'"q" (string), "options" (list of exactly 4 strings), "answer" (0-based index of '
            f'the correct option), "explain" (short bilingual explanation). No extra text.'
        )
        res = client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[{"role": "system", "content": "You are a Class 10 exam question setter."},
                      {"role": "user", "content": prompt}],
            temperature=0.7, stream=False,
        )
        raw = res.choices[0].message.content.strip()
        raw = raw[raw.find("["): raw.rfind("]") + 1]  # isolate the JSON array
        data = json.loads(raw)
        clean = []
        for it in data:
            if (isinstance(it.get("options"), list) and len(it["options"]) == 4
                    and isinstance(it.get("answer"), int) and 0 <= it["answer"] <= 3 and it.get("q")):
                clean.append({"q": it["q"], "options": it["options"],
                              "answer": it["answer"], "explain": it.get("explain", "")})
        return clean[:n]
    except Exception:
        return []


def get_questions(subject, n):
    """Return (questions, source_label)."""
    ai = _ai_generate(subject, n)
    if ai:
        return ai, "🤖 AI generated"
    pool = list(MCQ_BANK.get(subject, []))
    random.shuffle(pool)
    return pool[:n], "📖 Question bank"


def _clear_quiz():
    for k in list(st.session_state.keys()):
        if k.startswith("c10_"):
            del st.session_state[k]


def render_demo_class10_mcq():
    st.title("📝 Class 10 (Odia Medium) — Practice Test")
    st.caption("ବିଷୟ ବାଛନ୍ତୁ, ପ୍ରଶ୍ନର ଉତ୍ତର ଦିଅନ୍ତୁ, ଏବଂ ସ୍କୋର ସହ ବ୍ୟାଖ୍ୟା ପାଆନ୍ତୁ। "
               "(Pick a subject, answer the MCQs, get your score with explanations.)")

    subjects = list(SUBJECTS)
    c1, c2 = st.columns([2, 1])
    subject = c1.selectbox("ବିଷୟ / Subject", subjects,
                           format_func=lambda s: f"{SUBJECTS[s]} {s}")
    num = c2.selectbox("ପ୍ରଶ୍ନ ସଂଖ୍ୟା / No. of questions", [5, 10], index=0)

    if st.button("🚀 ପରୀକ୍ଷା ଆରମ୍ଭ କରନ୍ତୁ / Start Test", type="primary"):
        _clear_quiz()
        qs, label = get_questions(subject, num)
        st.session_state["c10_quiz"] = qs
        st.session_state["c10_subject"] = subject
        st.session_state["c10_label"] = label
        st.session_state["c10_submitted"] = False

    quiz = st.session_state.get("c10_quiz")
    if not quiz:
        st.info("ଉପରେ ବିଷୟ ବାଛି **Start Test** ଦବାନ୍ତୁ। / Choose a subject above and press Start Test.")
        return

    subject = st.session_state.get("c10_subject", subject)
    submitted = st.session_state.get("c10_submitted", False)

    st.markdown(f"### {SUBJECTS.get(subject,'')} {subject}  "
                f"<span style='font-size:13px;opacity:.7'>({st.session_state.get('c10_label','')})</span>",
                unsafe_allow_html=True)

    # ── Render questions ──
    for i, item in enumerate(quiz):
        with st.container(border=True):
            st.markdown(f"**ପ୍ରଶ୍ନ / Q{i+1}.** {item['q']}")
            st.radio("ଉତ୍ତର ବାଛନ୍ତୁ / Choose your answer:", item["options"],
                     index=None, key=f"c10_ans_{i}", disabled=submitted,
                     label_visibility="collapsed")
            if submitted:
                chosen = st.session_state.get(f"c10_ans_{i}")
                correct = item["options"][item["answer"]]
                if chosen == correct:
                    st.success(f"✅ ସଠିକ୍ / Correct — **{correct}**")
                elif chosen is None:
                    st.warning(f"⚠️ ଅନୁତ୍ତରିତ / Not answered — ସଠିକ୍ ଉତ୍ତର: **{correct}**")
                else:
                    st.error(f"❌ ଭୁଲ୍ / Wrong — ଆପଣଙ୍କ: {chosen} · ସଠିକ୍: **{correct}**")
                if item.get("explain"):
                    st.caption(f"💡 {item['explain']}")

    # ── Actions ──
    if not submitted:
        if st.button("✅ ଉତ୍ତର ଯାଞ୍ଚ କରନ୍ତୁ / Submit & Check", type="primary"):
            st.session_state["c10_submitted"] = True
            st.rerun()
        return

    # ── Score summary (after submit) ──
    score = sum(1 for i, item in enumerate(quiz)
                if st.session_state.get(f"c10_ans_{i}") == item["options"][item["answer"]])
    total = len(quiz)
    pct = round(100 * score / total) if total else 0
    color = "#0d9488" if pct >= 60 else ("#d97706" if pct >= 35 else "#dc2626")
    remark = ("ବହୁତ ଭଲ! / Excellent!" if pct >= 80 else
              "ଭଲ / Good — keep practising!" if pct >= 60 else
              "ଅଧିକ ଅଭ୍ୟାସ ଦରକାର / Needs more practice.")
    st.markdown(
        f"<div style='padding:18px 22px;border-radius:14px;text-align:center;color:#fff;"
        f"background:{color};font-size:18px;font-weight:800;'>ସ୍କୋର / Score: {score} / {total} "
        f"({pct}%)<div style='font-size:14px;font-weight:500;opacity:.95;margin-top:4px;'>"
        f"{remark}</div></div>",
        unsafe_allow_html=True,
    )

    b1, b2 = st.columns(2)
    if b1.button("🔁 ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ / New Test", use_container_width=True):
        _clear_quiz()
        st.rerun()
    if b2.button("📚 ଅନ୍ୟ ବିଷୟ / Another Subject", use_container_width=True):
        _clear_quiz()
        st.rerun()

    # ── Light sign-up nudge (full question bank behind free account) ──
    st.markdown(
        "<div style='margin-top:16px;padding:16px 20px;border-radius:14px;color:#fff;text-align:center;"
        "background:linear-gradient(135deg,#7c3aed,#0ea5e9);'>"
        "<b>ମାଗଣାରେ ସାଇନ୍ ଅପ୍ କରନ୍ତୁ</b> — ସବୁ ବିଷୟର ଅଧିକ ପ୍ରଶ୍ନ, ଅଧ୍ୟାୟ-ଅନୁସାରେ ଅଭ୍ୟାସ ଓ ପୂର୍ଣ୍ଣ ମକ୍ ଟେଷ୍ଟ। "
        "<br><span style='opacity:.9;font-size:14px;'>Sign up free for more questions per subject, "
        "chapter-wise practice, and full mock tests.</span></div>",
        unsafe_allow_html=True,
    )
    cta = st.columns([1, 2, 1])
    with cta[1]:
        if st.button("🔓 ମାଗଣା ଆକାଉଣ୍ଟ ଖୋଲନ୍ତୁ / Sign up free", type="primary",
                     use_container_width=True, key="c10_signup_cta"):
            st.session_state["auth_page"] = "signup"
            _clear_quiz()
            try:
                st.query_params.clear()
            except Exception:
                try:
                    st.experimental_set_query_params()
                except Exception:
                    pass
            st.rerun()


if __name__ == "__main__":
    st.set_page_config(page_title="Class 10 Odia Medium — Practice Test",
                       page_icon="📝", layout="centered")
    render_demo_class10_mcq()
